environments:
  default:
    domain: domain_var
    name: env_var
    profile_name: organization_var-env_var
    region: region_var
  permanent:
    - env_var
  temporary:
    secrets:
      firebase_credentials: DUMMY
      mail_password: DUMMY
general:
  organization: organization_var
  secrets_key_id: alias/secrets
sites:
  ordered:
